### ISSUE TITLE
Toplogy.residue() is broken

### ISSUE THREAD

**Issue by pindakaas42** [Amber-MD/pytraj#1525]
```
import pytraj as pt
p=pt.load_pdb_rcsb('126D')
p.top.residue(25).index == 25
p.top.residue(25).index
list(p.top[':26'].residues)[0].index == 25
list(p.top[':26'].residues)[0].index
```
In my estimation these both should return True right? Anyway `list(p.top[':26'].residues)[0].index`  as well as  `p.top.residue(25).index` return 36. This is not a problem of this specific pdb (as far as I can see).

**Comment by hainm** [comment]
yeah, agree. The `index` is a misleading name. It should be `original_index`. 
https://github.com/Amber-MD/pytraj/blob/6f91b6debd1e69a99de99d7ceeb661d5eea1a740/pytraj/core/topology_objects.pyx#L223-L226

pytraj needs to cleanup.

**Comment by pindakaas42** [comment]
But what does original resid mean in this context? 
Because index in this case, correctly returns the residue id as defined by the pdb, while` p.top.residue(k)` interprets the number k as the k-th residue entry in the pdb file, which pretty useless, as the sequence in the file is pretty much irrelevant.  

So I would say the index property is working, as I would expect, the top.residue() method is the problem. 
Maybe I should open another issue for the p.top[':26'] problem, because this also gives the wrong residue, meaning not the one with number 26, but the on at the 26-th place in the pdb (counting from 0).

**Comment by hainm** [comment]
> But what does original resid mean in this context?

The use case is here: #1528 

> while p.top.residue(k) interprets the number k as the k-th residue entry in the pdb file, which pretty useless, as the sequence in the file is pretty much irrelevant.

It's helpful to others. 
`p.top.residue(25)` is similar to `list(p.top.residues)[25]`.
Due to the implementation detail in `pytraj` and `cpptraj`, `p.top.residues` won't return a list of residues but a generator. 

Use case: Saying you cut a segment from residue 100-120. It's just easier for someone like me to think about 1st residue, 2nd residue in the segment rather than the 100th or 101th. It's just matter of counting.

**Comment by pindakaas42** [comment]
I don't follow, If I want to select the residue with the resid 25 what should I do in my example?
The API does not give me the possiblity, I'd have to iterate over all residues and compare .index to the one I'd like to select...

**Comment by hainm** [comment]
Please note that `pytraj` (and its C++ backend cpptraj) is not designed specifically for handle pdb file. It's for Amber simulation where the the residues always renumbered. So if you want to get residue with resid 25, it's `p.top.residue(25)`. 

Biopython seems to be better tool to deal with pdb.

**Comment by pindakaas42** [comment]
Okay I have come t

**Comment by hainm** [comment]
Close this issue since `pytraj` is for trajectory analysis, not for handling pdb file specifically.

**Comment by drroe** [comment]
Hi,

> I don't follow, If I want to select the residue with the resid 25 what should I do in my example?
> The API does not give me the possiblity, I'd have to iterate over all residues and compare .index to the one I'd like to select...
> 
> (Just to be clear, this is not a one of error p.top.residue(25).index returns 36 for example...)

I know I'm a little late to this discussion, but maybe I can clear some things up. In cpptraj (and throughout Amber in general) when we say "residue number", we're really referring to "residue index", i.e. the residue's position in the topology. This is is different then residue the residue number in a PDB file, which is really a label (and done so that it is easier to compare the same residue in different chains or between different variants of a protein, etc). In cpptraj, the residue number from the PDB is referred to as "original residue number" because I couldn't think of a better thing to call it. I have updated the cpptraj mask syntax (and I guess pytraj supports this as well) to make it possible to select via "original residue number" and/or chain ID via `:;` and `::` respectively.

**Comment by hainm** [comment]
> I have updated the cpptraj mask syntax (and I guess pytraj supports this as well) to make it possible to select via "original residue number" and/or chain ID via :; and :: respectively.

Cool. Thanks @drroe.
