### ISSUE TITLE
basic tutorial: hbond search

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#490]
```python
In [69]: import pytraj as pt

In [70]: pdb = pt.load_pdb_rcsb("1l2y")

In [71]: pdb
Out[71]:
<pytraj.Trajectory with 38 frames: <Topology with 304 atoms, 20 residues, 1 mols, 310 bonds, 
non-PBC>>


In [72]: dslist = pt.search_hbonds(pdb)

In [73]: h = pt.hbonds.HbondAnalysisResult(dslist)

In [74]: h
Out[74]: <pytraj.hbonds.HbondAnalysisResult at 0x2aac478062b0>

In [75]: h.lifetime(cut=0.5)
Out[75]:
{'ARG16_O-TRP6_NE1-HE1': 0.9473684210526315,
 'ILE4_O-LYS8_N-H': 0.7631578947368421,
 'LEU7_O-GLY10_N-H': 0.8947368421052632,
 'TYR3_O-LEU7_N-H': 1.0}
```

**TODO**: add text

**Comment by hainm** [comment]
a lot of Amber questions related to hbond, so I am making HbondanalysisResult (not really great name) to store the data (it hold DatasetList too) and to parse the result. For example, just use `lifetime(cut=0.5)` to print out all hbond having lifetime >= 0.5 (just a fraction of frames). not sure if I interpret the meaning of `lifetime` correctly for cpptraj.

**Comment by hainm** [comment]
lifetime between 0.5-1.
```python
In [34]: h.lifetime((0.5, 1.))
Out[34]:
{'ARG16_O-TRP6_NE1-HE1': 0.9473684210526315,
 'ILE4_O-LYS8_N-H': 0.7631578947368421,
 'LEU7_O-GLY10_N-H': 0.8947368421052632,
 'TYR3_O-LEU7_N-H': 1.0}
```

**Comment by mojyt** [comment]
Hi,

On Fri, Jun 26, 2015 at 7:58 PM, Hai Nguyen <notifications@github.com>
wrote:

> a lot of Amber questions related to hbond, so I am making
> HbondanalysisResult (not really great name) to store the data (it hold
> DatasetList too) and to parse the result. For example, just use
> lifetime(cut=0.5) to print out all hbond having lifetime >= 0.5 (just a
> fraction of frames). not sure if I interpret the meaning of lifetime
> correctly for cpptraj.
>

This isn't exactly what the 0.5 means. Lifetime essentially relates to the
statistics of something "when present", and in the context of hydrogen
bonding it means when the hydrogen bond is present. The 0.5 is a cutoff for
the hbond data sets to say when a hbond is present; since the hbond series
data sets have 0 for not present and 1 for present, greater than 0.5 means
hydrogen bond present. This example from the manual is a good one (I think):

Given the hbond time series data set {1 1 1 0 1 0 0 0 1 1}, the overall
fraction present is 0.6. However, there are 3 lifetimes of lengths 3, 1,
and 2 ({1 1 1}, {1}, and {1 1}). The maximum lifetime is 3 and the average
lifetime is 2.0, i.e. (3 + 1 + 2) / 3 lifetimes = 2.0.

Let me know if you have more questions.

-Dan


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytraj/pytraj/issues/490#issuecomment-115936111>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by hainm** [comment]
great. thanks.

Hai
