### ISSUE TITLE
speed: pytraj vs mdtraj with rmsd

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#521]
**Note** I have a ipython notebook before but I've just moved some codes from cython to python
to make faster code writing and testing. So just want to compare rmd calculation again.

```python
In [68]: traj # pytraj
Out[68]:
<pytraj.Trajectory with 1000 frames: <Topology with 17443 atoms, 5666 residues, 
1 mols, 17452 bonds, PBC with box type = truncoct>>


In [69]: t # mdtraj
Out[69]: <mdtraj.Trajectory with 1000 frames, 17443 atoms, 5666 residues, 
and unitcells at 0x2aaacc4155c0>
```

**Comment by hainm** [comment]
* calculate rmsd for all atoms

```python
In [70]: %timeit pt.rmsd(traj)
1 loops, best of 3: 1.23 s per loop
```

```python
In [71]: %timeit md.rmsd(t, t, 0)
10 loops, best of 3: 78.2 ms per loop
```

ack, `pytraj` is about 16 times slower `mdtraj`

**Comment by hainm** [comment]
* calculate rmsd with mask: all atoms but CA.

```python
In [74]: %timeit pt.rmsd(traj, mask='!@CA')
1 loops, best of 3: 1.23 s per loop
```

```python
In [78]: %timeit  md.rmsd(t, t, 0, atom_indices=top.select("not name CA"))
1 loops, best of 3: 3.34 s per loop
```

`pytraj` is about 2.7 times faster `mdtraj`. `cpptraj` mask selection works really fast.

assert result
```python
In [83]: md.rmsd(t, t, 0, atom_indices=top.select("not name CA")) - pt.rmsd(traj, mask='!@CA')
Out[83]:
array([  2.67918563e-03,  -8.99811927e-08,   7.49506999e-08, ...,
        -1.57568665e-07,  -1.52518040e-07,   7.24852627e-08])
```

**Comment by hainm** [comment]
@swails and @mojyt: FYI.

**Comment by hainm** [comment]
it's funny that if `mdtraj` use `pytraj.api.Trajectory` that I wrote a while ago, its rmsd calculation is even faster.

```python
In [122]: type(ta)
Out[122]: pytraj.api.Trajectory

In [123]: %timeit md.rmsd(ta, ta, 0)
10 loops, best of 3: 55 ms per loop

In [124]: type(t)
Out[124]: mdtraj.core.trajectory.Trajectory

In [125]: %timeit md.rmsd(t, t, 0)
10 loops, best of 3: 78.9 ms per loop
```

**Comment by mojyt** [comment]
I think this is because mdtraj employs quaternions in calculating RMSD,
right? At some size construction of the quaternion becomes more expensive
than calculation of the coordinate covariance matrix + Kabsch algorithm,
which is why I think you're seeing this timing behavior. I've thought about
getting quaternion into cpptraj at some point but it's competing with a lot
of other stuff on the to-do list...

On Wed, Jul 8, 2015 at 9:57 PM, Hai Nguyen <notifications@github.com> wrote:

>
>    - calculate rmsd with mask: all atoms but CA.
>
> In [74]: %timeit pt.rmsd(traj, mask='!@CA')1 loops, best of 3: 1.23 s per loop
>
> In [78]: %timeit  md.rmsd(t, t, 0, atom_indices=top.select("not name CA"))1 loops, best of 3: 3.34 s per loop
>
> pytraj is about 2.7 times faster mdtraj. cpptraj mask selection works
> really fast.
>
> assert result
>
> In [83]: md.rmsd(t, t, 0, atom_indices=top.select("not name CA")) - pt.rmsd(traj, mask='!@CA')
> Out[83]:
> array([  2.67918563e-03,  -8.99811927e-08,   7.49506999e-08, ...,
>         -1.57568665e-07,  -1.52518040e-07,   7.24852627e-08])
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytraj/pytraj/issues/521#issuecomment-119806489>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
It's not just the quaternion.  It's also the explicit SSE vector instructions they use to operate near the FLOP limit.  See [here](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/src/theobald_rmsd.c#L384-L494), for example.  And all of their calculations are done in single precision, which roughly doubles the number of coordinates that can fit in the registers.  If I'm not mistaken, cpptraj does all of its calculations in double precision, right?  So in the theoretically optimized limit, there's an inherent factor-of-two advantage for mdtraj off the bat.  (Please correct me if I'm wrong about any of that).

They do a *lot* of pairwise RMSD calculations, so it's very important to them to have an extremely high-performant RMSD implementation.  In practice, cpptraj's RMSD has never been rate-limiting for me (*ever*).

In pytraj, you have the freedom to speed up the RMSD calculation for free -- if `mdtraj` is available, run the RMSD calculation through their engine.  Otherwise, use the built-in one from cpptraj. :)

**Comment by mojyt** [comment]
Cool stuff, I wasn't aware of the SSE opts. Single precision is a nice
boost as well, although I don't think it's a factor of two in terms of CPU
cycles - most of the boost comes from being faster to load in memory right?
I wonder if they ever run into precision issues? I'm guessing they have
that all figured out and probably only weird corner cases might cause them
problems.

Cpptraj could still benefit from this in places like 2drms and cluster etc.
I still don't see myself getting to this any time soon.

On Thu, Jul 9, 2015 at 9:13 AM, Jason Swails <notifications@github.com>
wrote:

> It's not just the quaternion. It's also the explicit SSE vector
> instructions they use to operate near the FLOP limit. See here
> <https://github.com/mdtraj/mdtraj/blob/master/mdtraj/rmsd/src/theobald_rmsd.c#L384-L494>,
> for example. And all of their calculations are done in single precision,
> which roughly doubles the number of coordinates that can fit in the
> registers. If I'm not mistaken, cpptraj does all of its calculations in
> double precision, right? So in the theoretically optimized limit, there's
> an inherent factor-of-two advantage for mdtraj off the bat. (Please correct
> me if I'm wrong about any of that).
>
> They do a *lot* of pairwise RMSD calculations, so it's very important to
> them to have an extremely high-performant RMSD implementation. In practice,
> cpptraj's RMSD has never been rate-limiting for me (*ever*).
>
> In pytraj, you have the freedom to speed up the RMSD calculation for free
> -- if mdtraj is available, run the RMSD calculation through their engine.
> Otherwise, use the built-in one from cpptraj. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytraj/pytraj/issues/521#issuecomment-120027219>.
>



-- 
-------------------------
Daniel R. Roe, PhD
Department of Medicinal Chemistry
University of Utah
30 South 2000 East, Room 307
Salt Lake City, UT 84112-5820
http://home.chpc.utah.edu/~cheatham/
(801) 587-9652
(801) 585-6208 (Fax)

**Comment by swails** [comment]
> Cool stuff, I wasn't aware of the SSE opts. Single precision is a nice
> boost as well, although I don't think it's a factor of two in terms of CPU
> cycles - most of the boost comes from being faster to load in memory right?

In this case, I would say probably.  I can't imagine trajectory RMSD *not* being memory-bound.  But if they claim that they operate near the floating point limit, perhaps I'm wrong and the prefetch is effective in filling the cache with useful data without idling cycles.  In that case, single precision is faster on a CPU because you can run twice the number of ops with the same registers, right?

> Cpptraj could still benefit from this in places like 2drms and cluster etc.
> I still don't see myself getting to this any time soon.

Agreed.  Of course, MDTraj is LGPL, so I think you could just use their implementation if you wanted to.

**Comment by hainm** [comment]
@mojyt @swails 

I did the benchmark before and using float32 does speed up rmsd calculation a factor of two. 

```python
In [5]: traj.xyz.dtype
Out[5]: dtype('float64')

In [6]: %timeit md.rmsd(traj, traj, 0)
The slowest run took 14.59 times longer than the fastest. This could mean that an intermediate result is being cached
1000 loops, best of 3: 983 µs per loop

In [7]: traj2 = traj.copy()

In [8]: traj2.xyz = traj2.xyz.astype('f4')

In [9]: traj2.xyz.dtype
Out[9]: dtype('float32')

In [10]: %timeit md.rmsd(traj2, traj2, 0)
1000 loops, best of 3: 416 µs per loop
```

**Comment by hainm** [comment]
even with `cpptraj`, using float32 is slightly faster

```python
In [13]: %timeit pt.rmsd(traj, ref=0)
100 loops, best of 3: 6.27 ms per loop

In [14]: %timeit pt.rmsd(traj2, ref=0)
100 loops, best of 3: 4.86 ms per loop
```

**Comment by swails** [comment]
I don't think these benchmarks are very meaningful.  In particular, MDTraj will convert to single-precision floating point inside the `rmsd` routine before sending it off to the optimized C- routine.  So the extra time here is likely required to cast and copy the data before sending it off to the C RMSD function.

Same thing for cpptraj, except everything is cast to a double before being passed to the RMSD routine.  Not sure why `float32` is faster in that case since I don't know what's happening behind the scenes.  But if I had to guess, it's that there might be a number of conversions taking place behind-the-scenes.

**Comment by hainm** [comment]
> I don't think these benchmarks are very meaningful. In particular, MDTraj will convert to single-precision floating point inside the rmsd routine before sending it off to the optimized C- routine. So the extra time here is likely required to cast and copy the data before sending it off to the C RMSD function.

I see.

**Comment by swails** [comment]
It's an easy mistake to make when working in Python.  I started writing a different response before I realized that compiled routines can't change the precision of their runtime mode without using some kind of JIT compilation, which I know neither MDTraj nor cpptraj employs :)

**Comment by hainm** [comment]
@mojyt 
+100 if cluster analysis is much faster. I used to wait for > 1 day for clustering.

> Cpptraj could still benefit from this in places like 2drms and cluster etc.
I still don't see myself getting to this any time soon.

yeah, just wait for Gillian to write super badass GPU code. :P

**Comment by hainm** [comment]
close. Not worry about rmsd for now. (because cpptraj is fast, and rmsd calc is likely not the bottle-neck).
