### ISSUE TITLE
PCA: too much memory

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#845]
In the manual (29.14.2. Cartesian covariance matrix calculation and projection (PCA)

```bash
# Step one. Generate average structure.
# RMS-Fit to first frame to remove global translation/rotation.
parm data/tz2.parm7
trajin data/tz2.nc
rms first !@H=
average crdset AVG
run
# Step two. RMS-Fit to average structure. Calculate covariance matrix.
# Save the fit coordinates.
rms ref AVG !@H=
matrix covar name MyMatrix !@H=
createcrd CRD1
run
# Step three. Diagonalize matrix.
runanalysis diagmatrix MyMatrix vecs 2 name MyEvecs
# Step four. Project saved fit coordinates along eigenvectors 1 and 2
crdaction CRD1 projection evecs MyEvecs !@H= out project.dat beg 1 end 2
```

The `createcrd CRD1` step used up my RAM. Is the `createcrd` idiom for `projection`?

**Comment by drroe** [comment]
> The createcrd CRD1 step used up my RAM. Is the createcrd idiom for projection?

This is just one example of how one might use coordinates data sets to good effect; if your disk IO is slow it is much faster. You of course don't have to create a coordinates data set and can instead make multiple passes over the data, although you need to make sure you run the `rms` command prior to `projection`, otherwise the coordinates used in projection will not be the same as those used to create the covariance matrix.

It would probably be better to add a `strip` command to this example prior to fitting/calculating the matrix/creating the coordinates, which will save a good deal of memory (also means you can omit the `!@H=` mask in subsequent commands).

**Comment by hainm** [comment]
okie.
